# Game control elements
# SKY:
SKY_HEIGHT = 600
SKY_WIDTH = 600

# IMAGES:
ROCKET_IMG = "rocket.gif"
EXPLOSION = "explosion.gif"
ALIEN_IMG_G = "alien_invader.gif"
ALIEN_IMG_B = "alien_invader_B.gif"
ALIEN_IMG_R = "alien_invader_R.gif"
ALIEN_EXPLOSION = "alien_explosion.gif"

# SCOREBOARD:
SCORE_COLOR = "white"
LIFES = 3

# SHIP CONTROL:
ROCKET_STEP = 15
SHOT_LIMIT = 5
SHOT_DELAY = 2

# ALIEN CONTROL:
ALIENS_PER_LINE = 6
ALIENS_ROWS = 2
ALIENS_COUNT = ALIENS_ROWS * ALIENS_PER_LINE
ALIEN_INTERVAL_X = 85
ALIEN_INTERVAL_Y = 60
ALIEN_SIDE_STEP = 10
ALIEN_DOWN_STEP = 5
ALIEN_MAX_HEALTH = 5
ALIEN_ADVANCE_THRESHOLD = 4
ALIEN_RANDOMIZER = 5
ALIEN_FIRE_STEP = 10

# PLASMA CONTROL:
PLASMA_STEP = 10
SHOT_SPEED = 0.01


